/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampil;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import kelas.ClassEarsetAudio;
import koneksi.KoneksiAudio;

/**
 *
 * @author Kyrin
 */
public class MenuEarsetAudio extends javax.swing.JFrame {

    /**
     * Creates new form MenuEarsetAudio
     */
    
    private Connection conn = new KoneksiAudio().connect();
    private DefaultTableModel tabmode;
    
    protected static ClassEarsetAudio ClassES = new ClassEarsetAudio();

    protected void aktif() {
       txtMerkES.setEnabled(true);
       txtTipeES.setEnabled(true);
       txtWarnaES.setEnabled(true);
       txtEarbudES.setEnabled(true);
       txtHargaES.setEnabled(true);
       txtStokES.setEnabled(true);
       txtKodeES.requestFocus();
    }    

    protected void kosong() {
       txtKodeES.setText("");
       txtMerkES.setText("");
       txtTipeES.setText("");
       txtWarnaES.setText("");
       txtEarbudES.setText("");
       txtHargaES.setText("");
       txtStokES.setText("");
    }
    
    void masukin() {
        ClassES.setKodeES(txtKodeES.getText());
        ClassES.setMerkAlat(txtMerkES.getText());
        ClassES.setTipeAlat(txtTipeES.getText());
        ClassES.setWarnaAlat(txtWarnaES.getText());
        ClassES.setEarbudES(txtEarbudES.getText());
        ClassES.setHargaAlat(Integer.valueOf(txtHargaES.getText()));
        ClassES.setStokAlat(Integer.valueOf(txtStokES.getText()));
    }    
    
    protected void datatable() {
        Object[] Baris = {"Kode","Merk","Tipe","Warna","Earbud","Harga","Stok"};
        tabmode = new DefaultTableModel(null, Baris);
        tblEarset.setModel(tabmode);
        String sql = "SELECT * FROM tabel_earset";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
               String kd_es = hasil.getString("kdes");
               String merk_es = hasil.getString("merkes");
               String tipe_es = hasil.getString("tipees");
               String warna_es = hasil.getString("warnaes");
               String earbud_es = hasil.getString("modelearbud");
               String harga_es = hasil.getString("hargaes");
               String stok_es = hasil.getString("stokes");
               
               String[] data = {kd_es, merk_es, tipe_es, warna_es, earbud_es, harga_es, stok_es};
               tabmode.addRow(data);
            }
        } catch (Exception e) {

        }
    }    
    
    public MenuEarsetAudio() {
        initComponents();
        datatable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtStokES = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtTipeES = new javax.swing.JTextField();
        txtWarnaES = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtEarbudES = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEarset = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtKodeES = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMerkES = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtHargaES = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel5.setText("Warna");

        jLabel6.setText("Model Earbud");

        jLabel9.setText("Harga");

        jLabel10.setText("Stok");

        tblEarset.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEarset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEarsetMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEarset);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("DAFTAR EARSET");

        txtKodeES.setText("ES");

        jLabel2.setText("Kode");

        jLabel3.setText("Merk");

        jLabel4.setText("Tipe");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addGap(49, 49, 49))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(58, 58, 58)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMerkES, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                    .addComponent(txtKodeES, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTipeES, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtWarnaES, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel6))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEarbudES, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                    .addComponent(txtStokES, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtHargaES)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKodeES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtEarbudES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMerkES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTipeES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtHargaES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStokES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWarnaES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnDelete))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
        try{
            masukin();
            
            String sql = "INSERT INTO tabel_earset"
                + "(kdes, merkes, tipees, warnaes, modelearbud, hargaes, stokes) VALUES (?,?,?,?,?,?,?)";
            
            PreparedStatement stat = conn.prepareStatement(sql);

            if(txtKodeES.getText().equals("")||txtMerkES.getText().equals("")||txtTipeES.getText().equals("")
                ||txtWarnaES.getText().equals("")||txtEarbudES.getText().equals("")||txtHargaES.getText().equals("")
                ||txtStokES.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Input data terlebih dahulu!","ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                stat.setString(1, txtKodeES.getText());
                stat.setString(2, txtMerkES.getText());
                stat.setString(3, txtTipeES.getText());
                stat.setString(4, txtWarnaES.getText());
                stat.setString(5, txtEarbudES.getText());
                stat.setInt(6, Integer.valueOf(txtHargaES.getText()));
                stat.setInt(7, Integer.valueOf(txtStokES.getText()));
                
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil diinsert!");

                kosong();
                txtKodeES.requestFocus();
                datatable();
            }
        } catch (Exception except) {
            JOptionPane.showMessageDialog(null, ("Error!\n"+except));
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan menghapus data?", "Hapus Data",JOptionPane.YES_NO_OPTION);
        if(ok==0){
            String sql = "DELETE FROM tabel_earset WHERE kdes = '"+txtKodeES.getText()+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);

                if(txtKodeES.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(null, "Input Nomor Transaksi terlebih dahulu!","ERROR", JOptionPane.ERROR_MESSAGE);
                } else {
                    stat.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus! ");

                    kosong();
                    txtKodeES.requestFocus();
                    datatable();
                }
            } catch (Exception except) {
                JOptionPane.showMessageDialog(null, ("Error!\n"+except));
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        String sql = "UPDATE tabel_earset SET merkes=?, tipees=?, warnaes=?, modelearbud=?,"
        + "hargaes=?, stokes=? WHERE kdes='"+txtKodeES.getText()+"'";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);

            if(txtKodeES.getText().equals("")||txtMerkES.getText().equals("")||txtTipeES.getText().equals("")
                ||txtWarnaES.getText().equals("")||txtEarbudES.getText().equals("")
                ||txtHargaES.getText().equals("")||txtStokES.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Input data terlebih dahulu!","ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                stat.setString(1, txtMerkES.getText());
                stat.setString(2, txtTipeES.getText());
                stat.setString(3, txtWarnaES.getText());
                stat.setString(4, txtEarbudES.getText());
                stat.setString(5, txtHargaES.getText());
                stat.setString(6, txtStokES.getText());

                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil diupdate!");

                kosong();
                txtKodeES.requestFocus();
                datatable();
            }
        } catch (Exception except) {
            JOptionPane.showMessageDialog(null, ("Error!\n"+except));
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new MenuBarangAudio().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void tblEarsetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEarsetMouseClicked
        int bar = tblEarset.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        String g = tabmode.getValueAt(bar, 6).toString();

        txtKodeES.setText(a);
        txtMerkES.setText(b);
        txtTipeES.setText(c);
        txtWarnaES.setText(d);
        txtEarbudES.setText(e);
        txtHargaES.setText(f);
        txtStokES.setText(g);
    }//GEN-LAST:event_tblEarsetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEarsetAudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEarsetAudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEarsetAudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEarsetAudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEarsetAudio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEarset;
    private javax.swing.JTextField txtEarbudES;
    private javax.swing.JTextField txtHargaES;
    private javax.swing.JTextField txtKodeES;
    private javax.swing.JTextField txtMerkES;
    private javax.swing.JTextField txtStokES;
    private javax.swing.JTextField txtTipeES;
    private javax.swing.JTextField txtWarnaES;
    // End of variables declaration//GEN-END:variables
}
