/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampil;

import kelas.ClassHeadsetAudio;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.KoneksiAudio;

/**
 *
 * @author Kyrin
 */
public class MenuHeadsetAudio extends javax.swing.JFrame {

    /**
     * Creates new form MenuHeadsetAudio
     */

    private Connection conn = new KoneksiAudio().connect();
    private DefaultTableModel tabmode;
      
    protected static ClassHeadsetAudio ClassHS = new ClassHeadsetAudio();

    protected void aktif() {
       txtMerkHS.setEnabled(true);
       txtTipeHS.setEnabled(true);
       txtWarnaHS.setEnabled(true);
       txtEarcupHS.setEnabled(true);
       txtHeadbandHS.setEnabled(true);
       txtHargaHS.setEnabled(true);
       txtStokHS.setEnabled(true);
       txtKodeHS.requestFocus();
    }

    protected void kosong() {
       txtKodeHS.setText("");
       txtMerkHS.setText("");
       txtTipeHS.setText("");
       txtWarnaHS.setText("");
       txtEarcupHS.setText("");
       txtHeadbandHS.setText("");
       txtHargaHS.setText("");
       txtStokHS.setText("");
    }
    
    void masukin() {
        ClassHS.setKodeHS(txtKodeHS.getText());
        ClassHS.setMerkAlat(txtMerkHS.getText());
        ClassHS.setTipeAlat(txtTipeHS.getText());
        ClassHS.setWarnaAlat(txtWarnaHS.getText());
        ClassHS.setEarcupHS(txtEarcupHS.getText());
        ClassHS.setHeadbandHS(txtHeadbandHS.getText());
        ClassHS.setHargaAlat(Integer.valueOf(txtHargaHS.getText()));
        ClassHS.setStokAlat(Integer.valueOf(txtStokHS.getText()));
    }
    
    protected void datatable() {
        Object[] Baris = {"Kode","Merk","Tipe","Warna","Earcup","Headband","Harga","Stok"};
        tabmode = new DefaultTableModel(null, Baris);
        tblHeadset.setModel(tabmode);
        String sql = "SELECT * FROM tabel_headset";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
               String kd_hs = hasil.getString("kdhs");
               String merk_hs = hasil.getString("merkhs");
               String tipe_hs = hasil.getString("tipehs");
               String warna_hs = hasil.getString("warnahs");
               String earcup_hs = hasil.getString("modelearcup");
               String headband_hs = hasil.getString("warnaheadband");
               String harga_hs = hasil.getString("hargahs");
               String stok_hs = hasil.getString("stokhs");
               
               String[] data = {kd_hs, merk_hs, tipe_hs, warna_hs, earcup_hs, headband_hs, harga_hs, stok_hs};
               tabmode.addRow(data);
            }
        } catch (Exception e) {

        }
    }    
    
    public MenuHeadsetAudio() {
        initComponents();
        datatable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblHeadset = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtKodeHS = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMerkHS = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTipeHS = new javax.swing.JTextField();
        txtWarnaHS = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtEarcupHS = new javax.swing.JTextField();
        txtHeadbandHS = new javax.swing.JTextField();
        txtHargaHS = new javax.swing.JTextField();
        txtStokHS = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblHeadset.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblHeadset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHeadsetMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHeadset);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("DAFTAR HEADSET");

        txtKodeHS.setText("HS");

        jLabel2.setText("Kode");

        jLabel3.setText("Merk");

        jLabel4.setText("Tipe");

        jLabel5.setText("Warna");

        jLabel6.setText("Model Earcup");

        jLabel7.setText("Warna Headband");

        jLabel9.setText("Harga");

        jLabel10.setText("Stok");

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addGap(49, 49, 49))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(58, 58, 58)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMerkHS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                    .addComponent(txtKodeHS, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTipeHS, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtWarnaHS, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEarcupHS, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                    .addComponent(txtHeadbandHS, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtStokHS, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtHargaHS)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKodeHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtEarcupHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMerkHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTipeHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtWarnaHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave)
                            .addComponent(btnEdit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBack)
                            .addComponent(btnDelete)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtHeadbandHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel10)
                                .addGap(3, 3, 3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtHargaHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtStokHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try{
            masukin();
        
            String sql = "INSERT INTO tabel_headset"
                + "(kdhs, merkhs, tipehs, warnahs, modelearcup, warnaheadband,"
                + "hargahs, stokhs) VALUES (?,?,?,?,?,?,?,?)";
        
            PreparedStatement stat = conn.prepareStatement(sql);

            if(txtKodeHS.getText().equals("")||txtMerkHS.getText().equals("")||txtTipeHS.getText().equals("")
                    ||txtWarnaHS.getText().equals("")||txtEarcupHS.getText().equals("")||txtHeadbandHS.getText().equals("")
                    ||txtHargaHS.getText().equals("")||txtStokHS.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Input data terlebih dahulu!","ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                stat.setString(1, txtKodeHS.getText());
                stat.setString(2, txtMerkHS.getText());
                stat.setString(3, txtTipeHS.getText());
                stat.setString(4, txtWarnaHS.getText());
                stat.setString(5, txtEarcupHS.getText());
                stat.setString(6, txtHeadbandHS.getText());
                stat.setInt(7, Integer.valueOf(txtHargaHS.getText()));
                stat.setInt(8, Integer.valueOf(txtStokHS.getText()));
                
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil diinsert!");
                
                kosong();
                txtKodeHS.requestFocus();
                datatable();    
            }
        } catch (Exception except) {
            JOptionPane.showMessageDialog(null, ("Error!\n"+except));
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tblHeadsetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHeadsetMouseClicked
        int bar = tblHeadset.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        String g = tabmode.getValueAt(bar, 6).toString();
        String h = tabmode.getValueAt(bar, 7).toString();
        
        txtKodeHS.setText(a);
        txtMerkHS.setText(b);
        txtTipeHS.setText(c);
        txtWarnaHS.setText(d);
        txtEarcupHS.setText(e);
        txtHeadbandHS.setText(f);
        txtHargaHS.setText(g);
        txtStokHS.setText(h);
    }//GEN-LAST:event_tblHeadsetMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan menghapus data?", "Hapus Data",JOptionPane.YES_NO_OPTION);
        if(ok==0){
            String sql = "DELETE FROM tabel_headset WHERE kdhs = '"+txtKodeHS.getText()+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                
                if(txtKodeHS.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(null, "Input Nomor Transaksi terlebih dahulu!","ERROR", JOptionPane.ERROR_MESSAGE);
                return;
                } else {  
                    stat.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus! ");
                
                    kosong();
                    txtKodeHS.requestFocus();
                    datatable();
                }
            } catch (Exception except) {
                JOptionPane.showMessageDialog(null, ("Error!\n"+except));
            }               
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        String sql = "UPDATE tabel_headset SET merkhs=?, tipehs=?, warnahs=?, modelearcup=?,"
                + "warnaheadband=?, hargahs=?, stokhs=? WHERE kdhs='"+txtKodeHS.getText()+"'";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            
            if(txtKodeHS.getText().equals("")||txtMerkHS.getText().equals("")||txtTipeHS.getText().equals("")
                    ||txtWarnaHS.getText().equals("")||txtEarcupHS.getText().equals("")||txtHeadbandHS.getText().equals("")
                    ||txtHargaHS.getText().equals("")||txtStokHS.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Input data terlebih dahulu!","ERROR", JOptionPane.ERROR_MESSAGE);
            return;
            } else {
                stat.setString(1, txtMerkHS.getText());
                stat.setString(2, txtTipeHS.getText());
                stat.setString(3, txtWarnaHS.getText());
                stat.setString(4, txtEarcupHS.getText());
                stat.setString(5, txtHeadbandHS.getText());
                stat.setString(6, txtHargaHS.getText());
                stat.setString(7, txtStokHS.getText());
            
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil diupdate!");
            
                kosong();
                txtKodeHS.requestFocus();
                datatable();
            }
        } catch (Exception except) {
            JOptionPane.showMessageDialog(null, ("Error!\n"+except));
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
            new MenuBarangAudio().setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuHeadsetAudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuHeadsetAudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuHeadsetAudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuHeadsetAudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuHeadsetAudio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHeadset;
    private javax.swing.JTextField txtEarcupHS;
    private javax.swing.JTextField txtHargaHS;
    private javax.swing.JTextField txtHeadbandHS;
    private javax.swing.JTextField txtKodeHS;
    private javax.swing.JTextField txtMerkHS;
    private javax.swing.JTextField txtStokHS;
    private javax.swing.JTextField txtTipeHS;
    private javax.swing.JTextField txtWarnaHS;
    // End of variables declaration//GEN-END:variables
}
